### ISSUE TITLE
Howto steps - usb device permissions

### ISSUE THREAD

**Issue by neural-loop** [TomWisnowski/pyrow#4]
When I try to run statshow.py in the venv

```
(venv) pi@raspberrypi:~/Projects/pyrow/src $ python statshow.py
EXCEPTION
Traceback (most recent call last):
  File "statshow.py", line 30, in <module>
    work_out_machine = pyrow.pyrow(machines_list[0])
  File "/home/pi/Projects/pyrow/src/pyrow.py", line 39, in __init__
    usb.util.claim_interface(erg, INTERFACE)
  File "/home/pi/Projects/pyrow/src/usb/util.py", line 191, in claim_interface
    device._ctx.managed_claim_interface(device, interface)
  File "/home/pi/Projects/pyrow/src/usb/core.py", line 103, in managed_claim_interface
    self.managed_open()
  File "/home/pi/Projects/pyrow/src/usb/core.py", line 70, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/home/pi/Projects/pyrow/src/usb/backend/libusb10.py", line 494, in open_device
    _check(_lib.libusb_open(dev.devid, byref(handle)))
  File "/home/pi/Projects/pyrow/src/usb/backend/libusb10.py", line 403, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
Exception ignored in: <function _Initializer.__del__ at 0x7645ea08>
Traceback (most recent call last):
  File "/home/pi/Projects/pyrow/src/usb/backend/libusb10.py", line 436, in __del__
AttributeError: 'NoneType' object has no attribute 'libusb_exit'
```

**Comment by neural-loop** [comment]
```
(venv) pi@raspberrypi:~/Projects/pyrow/src $ sudo adduser pi plugdev
The user `pi' is already a member of `plugdev'.
```

**Comment by neural-loop** [comment]
```
(venv) pi@raspberrypi:~/Projects/pyrow/src $ lsusb
Bus 001 Device 005: ID 17a4:0001 Concept2 Performance Monitor 3
Bus 001 Device 004: ID 0424:7800 Standard Microsystems Corp.
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

**Comment by neural-loop** [comment]
`SUBSYSTEM=="usb", ATTR{idVendor}=="17a4", ATTR{idProduct}=="0001", MODE="0666"`

**Comment by neural-loop** [comment]
copied above line into /etc/udev/rules.d/99-pm3.rules

note, pm5 uses idProduct 0003 I believe

**Comment by neural-loop** [comment]
```
(venv) pi@raspberrypi:~/Projects/pyrow/src $ python statshow.py
Connected to erg.
results1 {'CSAFE_GETSTATUS_CMD': [17], 'CSAFE_PM_GET_WORKOUTSTATE': [0], 'CSAFE_PM_GET_STROKESTATE': [0], 'CSAFE_GETVERSION_CMD': [22, 2, 3, 321, 315], 'CSAFE_GETID_CMD': ['00000'], 'CSAFE_GETUNITS_CMD': [0], 'CSAFE_GETSERIAL_CMD': ['400091003']}
results2 {'CSAFE_GETSTATUS_CMD': [129], 'CSAFE_GETODOMETER_CMD': [646783, 36], 'CSAFE_GETERRORCODE_CMD': [0], 'CSAFE_GETTWORK_CMD': [0, 0, 0], 'CSAFE_GETHORIZONTAL_CMD': [0, 36], 'CSAFE_GETCALORIES_CMD': [0], 'CSAFE_GETPROGRAM_CMD': [0], 'CSAFE_GETPACE_CMD': [0, 57], 'CSAFE_GETCADENCE_CMD': [0, 84], 'CSAFE_GETUSERINFO_CMD': [793, 40, 0, 0], 'CSAFE_GETHRCUR_CMD': [0], 'CSAFE_GETPOWER_CMD': [0, 88]}
State 1: Ready
Stroke 0: Wait for min speed
Workout 0: Waiting begin
results1 {'CSAFE_GETSTATUS_CMD': [17], 'CSAFE_PM_GET_WORKOUTSTATE': [0], 'CSAFE_PM_GET_STROKESTATE': [0], 'CSAFE_GETVERSION_CMD': [22, 2, 3, 321, 315], 'CSAFE_GETID_CMD': ['00000'], 'CSAFE_GETUNITS_CMD': [0], 'CSAFE_GETSERIAL_CMD': ['400091003']}
results2 {'CSAFE_GETSTATUS_CMD': [129], 'CSAFE_GETODOMETER_CMD': [646783, 36], 'CSAFE_GETERRORCODE_CMD': [0], 'CSAFE_GETTWORK_CMD': [0, 0, 0], 'CSAFE_GETHORIZONTAL_CMD': [0, 36], 'CSAFE_GETCALORIES_CMD': [0], 'CSAFE_GETPROGRAM_CMD': [0], 'CSAFE_GETPACE_CMD': [0, 57], 'CSAFE_GETCADENCE_CMD': [0, 84], 'CSAFE_GETUSERINFO_CMD': [793, 40, 0, 0], 'CSAFE_GETHRCUR_CMD': [0], 'CSAFE_GETPOWER_CMD': [0, 88]}
```
